# Generated by Django 4.2.4 on 2023-09-01 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('lastName', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('city', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('state', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('pincode', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('address', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('email', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('residence_owned_by', models.CharField(choices=[('owned by parent/sibling', 'owned by parent/sibling'), ('owned by self/spouse', 'owned by self/spouse'), ('rented - staying alone', 'rented - staying alone'), ('rented with family', 'rented with family')], max_length=100)),
                ('employment_Details', models.CharField(choices=[('', ''), ('', '')], max_length=100)),
                ('occupation', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
        ),
    ]
