# Generated by Django 4.2.4 on 2023-09-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='employment_Details',
            field=models.CharField(choices=[('self employeed business', 'self employeed business'), ('self employeed professional', 'self employeed professional')], max_length=100),
        ),
    ]
