# Generated by Django 4.2.4 on 2023-09-04 04:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0007_loancategory_loanrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='amount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000000)]),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='year',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
